
version: '3.5'

services:
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    expose:
      - '${XMPP_PORT:-5222}'
      - '${PROSODY_S2S_PORT:-5269}'
      - '5347'
      - '${PROSODY_HTTP_PORT:-5280}'
    labels:
      service: "jitsi-prosody"
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
      - ${CONFIG}/certs:/config/certs:Z

    environment:
      - AUTH_TYPE
      - DISABLE_POLLS
      - ENABLE_AUTH
      - ENABLE_AV_MODERATION
      - ENABLE_BREAKOUT_ROOMS
      - ENABLE_END_CONFERENCE
      - ENABLE_GUESTS
      - ENABLE_IPV6
      - ENABLE_LOBBY
      - ENABLE_RECORDING
      - ENABLE_S2S
      - ENABLE_TRANSCRIPTIONS
      - ENABLE_VISITORS
      - ENABLE_XMPP_WEBSOCKET
      - ENABLE_JAAS_COMPONENTS
      - GC_TYPE
      - GC_INC_TH
      - GC_INC_SPEED
      - GC_INC_STEP_SIZE
      - GC_GEN_MIN_TH
      - GC_GEN_MAX_TH
      - GLOBAL_CONFIG
      - GLOBAL_MODULES
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_SIP_BREWERY_MUC
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JICOFO_COMPONENT_SECRET
      - JIGASI_TRANSCRIBER_PASSWORD
      - JIGASI_TRANSCRIBER_USER
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_ENABLE_DOMAIN_VERIFICATION
      - JWT_SIGN_TYPE
      - JWT_TOKEN_AUTH_MODULE
      - MATRIX_UVS_URL
      - MATRIX_UVS_ISSUER
      - MATRIX_UVS_AUTH_TOKEN
      - MATRIX_UVS_SYNC_POWER_LEVELS
      - MATRIX_LOBBY_BYPASS
      - LOG_LEVEL
      - LDAP_AUTH_METHOD
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_VERSION
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - LDAP_URL
      - LDAP_USE_TLS
      - MAX_PARTICIPANTS
      - PROSODY_ADMINS
      - PROSODY_AUTH_TYPE
      - PROSODY_C2S_LIMIT
      - PROSODY_C2S_REQUIRE_ENCRYPTION
      - PROSODY_RESERVATION_ENABLED
      - PROSODY_RESERVATION_REST_BASE_URL
      - PROSODY_DISABLE_C2S_LIMIT
      - PROSODY_DISABLE_S2S_LIMIT
      - PROSODY_ENABLE_FILTER_MESSAGES
      - PROSODY_ENABLE_RATE_LIMITS
      - PROSODY_ENABLE_RECORDING_METADATA
      - PROSODY_ENABLE_STANZA_COUNTS
      - PROSODY_ENABLE_S2S
      - PROSODY_ENABLE_METRICS
      - PROSODY_GUEST_AUTH_TYPE
      - PROSODY_HTTP_PORT
      - PROSODY_LOG_CONFIG
      - PROSODY_METRICS_ALLOWED_CIDR
      - PROSODY_MODE
      - PROSODY_RATE_LIMIT_LOGIN_RATE
      - PROSODY_RATE_LIMIT_SESSION_RATE
      - PROSODY_RATE_LIMIT_TIMEOUT
      - PROSODY_RATE_LIMIT_ALLOW_RANGES
      - PROSODY_RATE_LIMIT_CACHE_SIZE
      - PROSODY_S2S_LIMIT
      - PROSODY_S2S_PORT
      - PROSODY_TRUSTED_PROXIES
      - PROSODY_VISITOR_INDEX
      - PROSODY_VISITORS_MUC_PREFIX
      - PROSODY_VISITORS_S2S_VHOSTS
      - PUBLIC_URL
      - STUN_HOST
      - STUN_PORT
      - TURN_CREDENTIALS
      - TURN_USERNAME
      - TURN_PASSWORD
      - TURN_HOST
      - TURNS_HOST
      - TURN_PORT
      - TURNS_PORT
      - TURN_TRANSPORT
      - TURN_TTL
      - TZ
      - VISITORS_MAX_VISITORS_PER_NODE
      - VISITORS_XMPP_DOMAIN
      - VISITORS_XMPP_SERVER
      - VISITORS_XMPP_PORT
      - XMPP_BREAKOUT_MUC_MODULES
      - XMPP_CONFIGURATION
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_LOBBY_MUC_MODULES
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_MUC_CONFIGURATION
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_HIDDEN_DOMAIN
      - XMPP_PORT
      - XMPP_RECORDER_DOMAIN
      - XMPP_SERVER_S2S_PORT
      - XMPP_SPEAKERSTATS_MODULES

networks:
  meet.jitsi:
