version: '3'

services:
    # Frontend
    nginx:
        image: nginx:latest
        restart: ${RESTART_POLICY}
        tty: true
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ./nginx/config:/etc/nginx
            - ./certs:/certs
            - /var/log/nginx:/var/log/nginx
            
        networks:
            blammonet:

    # XMPP server
    prosody:
        image: jitsi/prosody:latest
        restart: ${RESTART_POLICY}
        expose:
            - '5222'
            - '5347'
            - '5280'
        ports:
            - '5222:5222'
            - '5347:5347'
            - '5280:5280'
        volumes:
            - ./prosody/config:/config
            - /var/log/prosody:/var/log/prosody
            - ./prosody/plugins_custom//prosody-plugins-custom


# Custom network so all services can communicate using a FQDN
networks:
    blammonet:
